import {
  Job,
  Company,
  Keyword,
  DigestSettings,
  DashboardStats,
} from '@/types';

const today = new Date();
const yesterday = new Date(today.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000);
const fiveDaysAgo = new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000);
const tenDaysAgo = new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000);

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'Vercel',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    jobType: 'full-time',
    source: 'custom',
    dateFound: today,
    jobLink: 'https://vercel.com/careers/senior-frontend-engineer',
    description:
      'Looking for an experienced Frontend Engineer to join our platform team.',
    matchScore: 95,
    tags: ['Frontend', 'React', 'TypeScript', 'Next.js', 'Senior'],
    isSaved: true,
  },
  {
    id: '2',
    title: 'Full Stack Engineer',
    company: 'Stripe',
    location: 'Remote',
    locationType: 'remote',
    jobType: 'full-time',
    source: 'greenhouse',
    dateFound: today,
    jobLink: 'https://stripe.com/jobs/listing/full-stack-engineer',
    description: 'Build APIs and infrastructure at scale.',
    matchScore: 88,
    tags: ['Full-stack', 'Node.js', 'TypeScript', 'Remote'],
    isSaved: false,
  },
  {
    id: '3',
    title: 'React Developer',
    company: 'Figma',
    location: 'San Francisco, CA',
    locationType: 'on-site',
    jobType: 'full-time',
    source: 'lever',
    dateFound: yesterday,
    jobLink: 'https://figma.com/careers/react-developer',
    description: 'Join our design tools team and shape the future of design.',
    matchScore: 92,
    tags: ['Frontend', 'React', 'JavaScript', 'Design Systems'],
    isSaved: true,
  },
  {
    id: '4',
    title: 'Junior Frontend Engineer',
    company: 'GitHub',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    jobType: 'full-time',
    source: 'custom',
    dateFound: twoDaysAgo,
    jobLink: 'https://github.com/careers/junior-frontend',
    description: 'Entry-level position for developers with a passion for open source.',
    matchScore: 85,
    tags: ['Frontend', 'React', 'JavaScript', 'Junior', 'Graduate'],
    isSaved: false,
  },
  {
    id: '5',
    title: 'Backend Engineer - Node.js',
    company: 'Notion',
    location: 'San Francisco, CA',
    locationType: 'remote',
    jobType: 'full-time',
    source: 'ashby',
    dateFound: yesterday,
    jobLink: 'https://notion.so/careers/backend-engineer',
    description: 'Build scalable backend systems using Node.js.',
    matchScore: 78,
    tags: ['Backend', 'Node.js', 'TypeScript', 'Remote'],
    isSaved: false,
  },
  {
    id: '6',
    title: 'Frontend Intern',
    company: 'Netflix',
    location: 'Los Gatos, CA',
    locationType: 'on-site',
    jobType: 'internship',
    source: 'custom',
    dateFound: tenDaysAgo,
    jobLink: 'https://netflix.com/careers/frontend-intern',
    description: 'Summer internship for students passionate about web development.',
    matchScore: 82,
    tags: ['Frontend', 'React', 'Internship', 'Entry Level'],
    isSaved: true,
  },
  {
    id: '7',
    title: 'Software Engineer',
    company: 'Google',
    location: 'Mountain View, CA',
    locationType: 'on-site',
    jobType: 'full-time',
    source: 'greenhouse',
    dateFound: fiveDaysAgo,
    jobLink: 'https://google.com/careers/software-engineer',
    description: 'Build products that impact billions of users.',
    matchScore: 75,
    tags: ['Backend', 'JavaScript', 'Python', 'System Design'],
    isSaved: false,
  },
  {
    id: '8',
    title: 'TypeScript Developer',
    company: 'Airbnb',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    jobType: 'full-time',
    source: 'lever',
    dateFound: twoDaysAgo,
    jobLink: 'https://airbnb.com/careers/typescript-developer',
    description: 'Work on our platform using TypeScript and modern web technologies.',
    matchScore: 90,
    tags: ['Full-stack', 'TypeScript', 'React', 'Node.js'],
    isSaved: false,
  },
  {
    id: '9',
    title: 'React Native Engineer',
    company: 'Meta',
    location: 'Remote',
    locationType: 'remote',
    jobType: 'full-time',
    source: 'custom',
    dateFound: today,
    jobLink: 'https://meta.com/careers/react-native-engineer',
    description: 'Build mobile experiences using React Native.',
    matchScore: 72,
    tags: ['Mobile', 'React Native', 'JavaScript', 'Remote'],
    isSaved: false,
  },
  {
    id: '10',
    title: 'Senior Full Stack Engineer',
    company: 'Stripe',
    location: 'Remote',
    locationType: 'remote',
    jobType: 'full-time',
    source: 'greenhouse',
    dateFound: yesterday,
    jobLink: 'https://stripe.com/jobs/listing/senior-full-stack',
    description: 'Lead our infrastructure initiatives and mentor junior engineers.',
    matchScore: 91,
    tags: ['Full-stack', 'TypeScript', 'Node.js', 'Remote', 'Senior'],
    isSaved: true,
  },
];

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'Vercel',
    careerPageUrl: 'https://vercel.com/careers',
    sourceType: 'custom',
    lastChecked: new Date(today.getTime() - 2 * 60 * 60 * 1000), // 2 hours ago
    jobsFound: 3,
    status: 'active',
  },
  {
    id: '2',
    name: 'Stripe',
    careerPageUrl: 'https://stripe.com/jobs',
    sourceType: 'greenhouse',
    lastChecked: new Date(today.getTime() - 1 * 60 * 60 * 1000), // 1 hour ago
    jobsFound: 12,
    status: 'active',
  },
  {
    id: '3',
    name: 'Figma',
    careerPageUrl: 'https://figma.com/careers',
    sourceType: 'lever',
    lastChecked: new Date(today.getTime() - 3 * 60 * 60 * 1000), // 3 hours ago
    jobsFound: 5,
    status: 'active',
  },
  {
    id: '4',
    name: 'GitHub',
    careerPageUrl: 'https://github.com/careers',
    sourceType: 'custom',
    lastChecked: yesterday,
    jobsFound: 8,
    status: 'active',
  },
  {
    id: '5',
    name: 'Notion',
    careerPageUrl: 'https://notion.so/careers',
    sourceType: 'ashby',
    lastChecked: twoDaysAgo,
    jobsFound: 4,
    status: 'active',
  },
  {
    id: '6',
    name: 'Netflix',
    careerPageUrl: 'https://netflix.com/careers',
    sourceType: 'custom',
    lastChecked: new Date(today.getTime() - 5 * 60 * 60 * 1000), // 5 hours ago
    jobsFound: 2,
    status: 'active',
  },
  {
    id: '7',
    name: 'Google',
    careerPageUrl: 'https://google.com/careers',
    sourceType: 'greenhouse',
    lastChecked: tenDaysAgo,
    jobsFound: 25,
    status: 'active',
  },
  {
    id: '8',
    name: 'Airbnb',
    careerPageUrl: 'https://airbnb.com/careers',
    sourceType: 'lever',
    lastChecked: fiveDaysAgo,
    jobsFound: 7,
    status: 'failed',
  },
  {
    id: '9',
    name: 'Meta',
    careerPageUrl: 'https://meta.com/careers',
    sourceType: 'custom',
    lastChecked: today,
    jobsFound: 18,
    status: 'pending',
  },
];

export const mockKeywords: Keyword[] = [
  { id: '1', keyword: 'frontend', createdAt: tenDaysAgo },
  { id: '2', keyword: 'full-stack', createdAt: tenDaysAgo },
  { id: '3', keyword: 'software engineer', createdAt: fiveDaysAgo },
  { id: '4', keyword: 'react', createdAt: tenDaysAgo },
  { id: '5', keyword: 'next.js', createdAt: fiveDaysAgo },
  { id: '6', keyword: 'typescript', createdAt: tenDaysAgo },
  { id: '7', keyword: 'node.js', createdAt: fiveDaysAgo },
  { id: '8', keyword: 'graduate', createdAt: twoDaysAgo },
  { id: '9', keyword: 'intern', createdAt: tenDaysAgo },
  { id: '10', keyword: 'junior', createdAt: tenDaysAgo },
  { id: '11', keyword: 'entry level', createdAt: yesterday },
];

export const mockDigestSettings: DigestSettings = {
  id: '1',
  enabled: true,
  emailAddress: 'your.email@example.com',
  frequency: 'daily',
  preferredTime: '09:00',
  minimumMatchScore: 75,
};

export const mockDashboardStats: DashboardStats = {
  totalJobs: mockJobs.length,
  newJobsToday: mockJobs.filter(
    (job) =>
      job.dateFound.toDateString() === today.toDateString()
  ).length,
  companiesTracked: mockCompanies.length,
  savedJobs: mockJobs.filter((job) => job.isSaved).length,
  lastScrapeTime: new Date(today.getTime() - 30 * 60 * 1000), // 30 minutes ago
};
